trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
  
steps:
- task: CmdLine@2
  displayName: Checkout $(BUILD_SOURCEBRANCHNAME)
  inputs:
    script: 'git checkout $(BUILD_SOURCEBRANCHNAME)'

- script: curl -L 'https://get.spectralops.io/latest/x/sh?dsn=$(SPECTRAL_DSN)' | sh
  displayName: 'Install Spectral'
- script: $HOME/.spectral/spectral scan --dsn $(SPECTRAL_DSN) --include-tags base,audit3,iac
  displayName: 'Spectral Scan'
