trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
  
steps:
- task: CmdLine@2
  displayName: Checkout $(BUILD_SOURCEBRANCHNAME)
  inputs:
    script: 'git checkout $(BUILD_SOURCEBRANCHNAME)'

- script: curl -L 'https://spectral-eu.checkpoint.com/latest/x/sh?dsn=$(SPECTRAL_DSN)' | sh
  displayName: 'Install Spectral'
- script: $HOME/.spectral/spectral scan --ok --dsn $(SPECTRAL_DSN) --include-tags base,audit,iac
  displayName: 'Spectral Scan'
